import{a as d,S as f,i as a}from"./assets/vendor-MgecxatS.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();function m(e){return d.get("https://pixabay.com/api/",{params:{key:"53391226-a2ec73fe425479568eec525bb",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true"}}).then(r=>r.data).catch(r=>console.log(r))}let g=new f(".gallery a",{captionsData:"alt",captionDelay:250,close:!0,docClose:!1});const i=document.querySelector(".gallery");function y(e){return`<li class='gallery-item'>
    <a class='gallery-link' href=${e.largeImageURL}>
    <img class='gallery-image' src='${e.webformatURL}' alt='${e.tags}'/>
    <div class='img'>
    <p><strong>Likes</strong> ${e.likes}</p>
    <p><strong>Views</strong> ${e.views}</p>
    <p><strong>Comments</strong> ${e.comments}</p>
    <p><strong>Downloads</strong> ${e.downloads}</p></div></a></li>`}function p(e){const r=e.map(y).join("");return i.insertAdjacentHTML("beforeend",r),g.refresh(),r}function h(){i.innerHTML=""}function L(){const e=document.getElementById("loader-overlay");e&&e.classList.remove("hidden")}function c(){const e=document.getElementById("loader-overlay");e&&e.classList.add("hidden")}const u=document.querySelector(".form"),v=u.elements["search-text"];c();u.addEventListener("submit",e=>{e.preventDefault();const r=e.target.elements["search-text"].value.trim();if(r.length!==0){if(!r){a.warning({title:"Warning",message:"Please enter a search term!"});return}L(),h(),m(r).then(n=>{if(n.hits.length===0){a.error({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}p(n.hits),v.value=""}).catch(n=>{a.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error(n)}).finally(()=>{c()})}});
//# sourceMappingURL=index.js.map
